version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_predictHealth
    environment:
      POSTGRES_DB: PatientSystem
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 853211
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb_predictHealth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
